# apiVersion ve kind - Kubernetes'e "bu dosya ne tür bir kaynak tanımlıyor" söylüyoruz
apiVersion: apps/v1
kind: Deployment
metadata:
  # Bu Deployment'ın ismi
  name: user-service
spec:
  # Kaç kopya (replica) çalıştırılacak - şimdilik 1 tane yeterli
  replicas: 1
  # selector - bu Deployment'ın hangi Pod'ları "kendi Pod'um" olarak tanıyacağını belirtir
  selector:
    matchLabels:
      app: user-service
  # template - oluşturulacak Pod'un şablonu
  template:
    metadata:
      # Pod'a etiket (label) veriyoruz - selector'daki ile eşleşmeli
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          # env - container'a "DATABASE_URL" ortam değişkenini veriyoruz
          # database.py artık bunu okuyup Kubernetes içindeki
          # gerçek PostgreSQL adresine bağlanacak
          env:
            - name: DATABASE_URL
              value: "postgresql+psycopg://berk:berk123@user-postgres:5432/userdb"
